# !/bin/sh 

OUT=results/creativityworkshop/seurat-baigneurs/mse-500lines-learned-col; imageopt --loss MSELoss --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/Baigneurs_a_Asnieres.jpg --snapshots-steps 100
OUT=results/creativityworkshop/seurat-baigneurs/LPIPS-500lines-learned-col; imageopt --loss LPIPSLoss --net vgg --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/Baigneurs_a_Asnieres.jpg --snapshots-steps 100

OUT=results/creativityworkshop/seurat-park/mse-500lines-learned-col; imageopt --loss MSELoss --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Georges_Seurat_park.jpg --snapshots-steps 100
OUT=results/creativityworkshop/seurat-park/LPIPS-500lines-learned-col; imageopt --loss LPIPSLoss --net vgg --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Georges_Seurat_park.jpg --snapshots-steps 100

OUT=results/creativityworkshop/picasso-doramaar/mse-500crs-learned-col; imageopt --loss MSELoss --crs 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Portrait_of_Dora_Maar.jpg --snapshots-steps 100
OUT=results/creativityworkshop/picasso-doramaar/LPIPS-500crs-learned-col; imageopt --loss LPIPSLoss --net vgg --crs 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Portrait_of_Dora_Maar.jpg --snapshots-steps 100

OUT=results/creativityworkshop/picasso-guernica/mse-500points-learned-col; imageopt --loss MSELoss --points 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/PicassoGuernica.jpg --snapshots-steps 100
OUT=results/creativityworkshop/picasso-guernica/LPIPS-500points-learned-col; imageopt --loss LPIPSLoss --net vgg --points 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/PicassoGuernica.jpg --snapshots-steps 100

OUT=results/creativityworkshop/munch-the-scream/mse-500lines-learned-col; imageopt --loss MSELoss --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Edvard_Munch_The_Scream.jpg --snapshots-steps 100
OUT=results/creativityworkshop/munch-the-scream/LPIPS-500lines-learned-col; imageopt --loss LPIPSLoss --net vgg --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Edvard_Munch_The_Scream.jpg --snapshots-steps 100

OUT=results/creativityworkshop/gauguin-arearea/mse-500lines-learned-col; imageopt --loss MSELoss --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Paul_Gauguin_Arearea.jpg --snapshots-steps 100
OUT=results/creativityworkshop/gauguin-arearea/LPIPS-500lines-learned-col; imageopt --loss LPIPSLoss --net vgg --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Paul_Gauguin_Arearea.jpg --snapshots-steps 100

OUT=results/creativityworkshop/vangogh-sunflowers/mse-500points-learned-col; imageopt --loss MSELoss --points 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Van_Gogh_sunflowers.jpg --snapshots-steps 100
OUT=results/creativityworkshop/vangogh-sunflowers/LPIPS-500points-learned-col; imageopt --loss LPIPSLoss --net vgg --points 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Van_Gogh_sunflowers.jpg --snapshots-steps 100

OUT=results/creativityworkshop/vangogh-starrynight/mse-500lines-learned-col; imageopt --loss MSELoss --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Van_Gogh_Starry_Night.jpg --snapshots-steps 100
OUT=results/creativityworkshop/vangogh-starrynight/LPIPS-500lines-learned-col; imageopt --loss LPIPSLoss --net vgg --lines 500 --init-sigma2 15.0 --opt-sigma2 --sigma2-lr 0.00001 --colour --invert --seed 1234 --width 300 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/creativityworkshop/Van_Gogh_Starry_Night.jpg --snapshots-steps 100
