# !/bin/sh 

OUT=results/imageopt-1000pts; imageopt --invert --seed 1234 --width 200 --points 1000 --init-sigma2 1.0 --final-sigma2 1.0 --loss BlurredMSELoss --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-1000lines-blurredmse; imageopt --invert --seed 1234 --width 200 --lines 1000 --init-sigma2 1.0 --final-sigma2 1.0 --loss BlurredMSELoss --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100

OUT=results/imageopt-500lines-mse; imageopt --loss MSELoss --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-blurredmse1.0ns; imageopt --loss BlurredMSELoss --no-symmetric --blur-sigma 1.0 --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-blurredmse3.0ns; imageopt --loss BlurredMSELoss --no-symmetric --blur-sigma 3.0 --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-blurredmse5.0ns; imageopt --loss BlurredMSELoss --no-symmetric --blur-sigma 5.0 --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-blurredmse1.0; imageopt --loss BlurredMSELoss --blur-sigma 1.0 --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100

OUT=results/imageopt-500lines-pyrmseO5I1; imageopt --loss PyrMSELoss --intervals 1 --octaves 5 --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-pyrmseO5I2; imageopt --loss PyrMSELoss --intervals 3 --octaves 5 --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-pyrmseO5I4; imageopt --loss PyrMSELoss --intervals 4 --octaves 5 --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100

OUT=results/imageopt-500lines-lpips-alex; imageopt --loss LPIPSLoss --net alex --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-lpips-vgg; imageopt --loss LPIPSLoss --net vgg --invert --seed 1234 --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100

OUT=results/imageopt-2000lines-lpips-vgg; imageopt --loss LPIPSLoss --net vgg --invert --seed 1234 --width 200 --lines 2000 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-3000lines-lpips-vgg; imageopt --loss LPIPSLoss --net vgg --invert --seed 1234 --width 200 --lines 3000 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
