#!/bin/sh 

OUT=results/imageopt-500lines-mse-seed0; imageopt --seed 0 --loss MSELoss --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-lpips-vgg-seed0; imageopt --seed 0 --loss LPIPSLoss --net vgg --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100

OUT=results/imageopt-500lines-mse-seed1; imageopt --seed 1 --loss MSELoss --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-lpips-vgg-seed1; imageopt --seed 1 --loss LPIPSLoss --net vgg --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100

OUT=results/imageopt-500lines-mse-seed2; imageopt --seed 2 --loss MSELoss --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-lpips-vgg-seed2; imageopt --seed 2 --loss LPIPSLoss --net vgg --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100

OUT=results/imageopt-500lines-mse-seed3; imageopt --seed 3 --loss MSELoss --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
OUT=results/imageopt-500lines-lpips-vgg-seed3; imageopt --seed 3 --loss LPIPSLoss --net vgg --invert --width 200 --lines 500 --init-sigma2 1.0 --final-sigma2 1.0 --iters 500 --lr 0.01 --init-raster $OUT/init.png --final-raster $OUT/final.png --init-pdf $OUT/init.pdf --final-pdf $OUT/final.pdf --snapshots-path $OUT data/pinkalley.jpg --snapshots-steps 100
